name: Test and Build

on: 
  push:
    branches:
      - fingrow-ci/cd

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run:  | 
          cd frontend
          npm install

      - name: Run Tests
        run: |
          cd frontend
          npm test

      - name: Build 
      - run: |
          cd frontend
          npm run build